# Generated by Django 4.1.2 on 2022-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_column='brand', max_length=30, null=True, verbose_name='Brand')),
                ('name', models.CharField(blank=True, db_column='name', max_length=30, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
