# Generated by Django 4.1.2 on 2022-10-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(blank=True, db_column='Username', max_length=100, null=True, verbose_name='Username')),
                ('created_date', models.DateTimeField(blank=True, db_column='created_date', null=True, verbose_name='Created_Date')),
                ('updated_date', models.DateTimeField(blank=True, db_column='updated_date', null=True, verbose_name='Updated_Date')),
                ('total_price', models.FloatField(blank=True, db_column='total_price', null=True, verbose_name='Total_Price')),
                ('total_weight', models.FloatField(blank=True, db_column='total_weight', null=True, verbose_name='Total_Weight')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, db_column='color', max_length=10, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, db_column='height', null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, db_column='image_url', max_length=200, null=True, verbose_name='Image_Url'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, db_column='price', null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, db_column='width', null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('price', models.FloatField(blank=True, db_column='price', null=True, verbose_name='Price')),
                ('weight', models.FloatField(blank=True, db_column='weight', null=True, verbose_name='Weight')),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True, verbose_name='Quantity')),
                ('product_name', models.CharField(blank=True, db_column='product_name', max_length=200, null=True, verbose_name='Product_Name')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.product')),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.cart')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
