# Generated by Django 4.1.2 on 2022-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_orderstatusschema_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusschema',
            name='status_name',
            field=models.CharField(blank=True, db_column='status_name', max_length=30, null=True, verbose_name='Status_Name'),
        ),
    ]
