# Generated by Django 4.1.2 on 2022-11-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_alter_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.product'),
        ),
    ]
