# Generated by Django 4.1.2 on 2022-11-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_alter_cartitem_cart_alter_cartitem_pd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, db_column='weight', null=True, verbose_name='Weight'),
        ),
    ]
