# Generated by Django 4.1.2 on 2022-11-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_remove_product_color_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchema',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(blank=True, db_column='username', max_length=100, null=True, verbose_name='Username')),
                ('created_date', models.DateTimeField(blank=True, db_column='created_date', null=True, verbose_name='Created_Date')),
                ('updated_date', models.DateTimeField(blank=True, db_column='updated_date', null=True, verbose_name='Updated_Date')),
                ('total_price', models.FloatField(blank=True, db_column='total_price', null=True, verbose_name='Total_Price')),
                ('total_weight', models.FloatField(blank=True, db_column='total_weight', null=True, verbose_name='Total_Weight')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.orderstatusschema')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
