# Generated by Django 4.1.2 on 2022-11-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_productdetail_orderitemschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pd_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.productdetail', unique=True),
        ),
    ]
