# Generated by Django 4.1.2 on 2022-11-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_product_pd_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='camera_behind',
            field=models.CharField(blank=True, db_column='camera_behind', max_length=100, null=True, verbose_name='Camera_Behind'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='camera_front',
            field=models.CharField(blank=True, db_column='camera_front', max_length=100, null=True, verbose_name='Camera_Front'),
        ),
    ]
